 steps:
     - name: 'gcr.io/cloud-builders/docker'
       entrypoint: 'bash'
       args: ['-c', 'docker login https://docker.pkg.github.com --username=haruelico --password=$$PASSWORD']
       secretEnv: ['PASSWORD']
     # build the container image
     - name: 'gcr.io/cloud-builders/docker'
       args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/image-minifier:$COMMIT_SHA', '.']
     # push the container image to Container Registry
     - name: 'gcr.io/cloud-builders/docker'
       args: ['push', 'asia.gcr.io/$PROJECT_ID/image-minifier:$COMMIT_SHA']
     # Deploy container image to Cloud Run
     - name: 'gcr.io/cloud-builders/gcloud'
       args:
       - 'run'
       - 'deploy'
       - 'image-minifier'
       - '--image'
       - 'asia.gcr.io/$PROJECT_ID/image-minifier:$COMMIT_SHA'
       - '--region'
       - 'asia-northeast1'
       - '--platform'
       - 'managed'
 images:
 - 'asia.gcr.io/$PROJECT_ID/image-minifier:$COMMIT_SHA'
 secrets:
 - kmsKeyName: projects/kusokoudokaigi-3/locations/global/keyRings/github-docker/cryptoKeys/github-token
   secretEnv:
    PASSWORD: CiQANk8b4iEn9wEOdjnrAQYSLF+ybi4hm4oCpcVQd05CicHoEIUSUQAT6fHFy5NeqVOREFmbJ26CkSYFGwbs/NvH3i53MrMQ3xM2FFtyrfVr1YqliR3xDkFDHE7BLG6mKRi11CQJ1e7BS3jnqFP4m10oj0YP8U+6LQ==
